### ISSUE TITLE
roadmap to v1.0.0

### ISSUE THREAD

**Issue by the-mikedavis** [NFIBrokerage/spear#7]
Here's the general plan:

- [x] v0.1.0: Streams API (`streams.proto`)
- [x] v0.1.1: Resolve #4
- [x] v0.1.2: Resolve #6
- [x] v0.1.3: TLS functionality & documentation
- [x] v0.2.0: keep-alive functionality and configuration validation
- [x] v0.3.0: Users API (`users.proto`)
- [x] v0.4.0: Operations API (`operations.proto`)
- [x] v0.5.0: Gossip API (`gossip.proto`)
- [x] v0.6.0: Persistent Subscriptions API (`persistent.proto`)
- [ ] v0.x.0: Projections API (`projections.proto`) (see #22)
- [x] Broadway integration for persistent subscriptions API
    - see [`NFIBrokerage/radical`](https://github.com/NFIBrokerage/radical) for the TCP-client driven version of this
    - https://github.com/NFIBrokerage/volley
- [ ] v1.0.0: tested and tried out in prod for a good while

**Comment by the-mikedavis** [comment]
We haven't felt any need to implement the projections API and we've been using Spear for a while in production so I think it's time for the v1.0.0 release.

**Comment by the-mikedavis** [comment]
v1.0.0 is released! https://github.com/NFIBrokerage/spear/releases/tag/v1.0.0
